osm: data-input/israel.osm.pbf

street_routing: true
geocoding: true
reverse_geocoding: true
osr_footpath: true

timetable:
  first_day: TODAY
  num_days: 365
  datasets:
    israel:
      path: data-input/israel-gtfs.zip

server:
  host: 127.0.0.1
  port: 3504
