package com.automatelinux.pt.util

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val routePlanner: String,
    val stationArrivals: String,
    val settings: String,
    val opacitySettings: String,
    val hideOpacitySettings: String,
    val sheet: String,
    val cards: String,
    val from: String,
    val to: String,
    val swapOriginDestination: String,
    val searchRoutes: String,
    val searchingRoutes: String,
    val retry: String,
    val now: String,
    val departAt: String,
    val arriveBy: String,
    val next: String,
    val cancel: String,
    val ok: String,
    val direct: String,
    val transferCount: (Int) -> String,
    val walkDescription: (duration: String, destination: String) -> String,
    val transitDescription: (mode: String, route: String, destination: String, duration: String) -> String,
    val showStops: (Int) -> String,
    val hideStops: (Int) -> String,
    val walkMode: String,
    val busMode: String,
    val trainMode: String,
    val tramMode: String,
    val subwayMode: String,
    val ferryMode: String,
    val formatDuration: (Long) -> String,
    val station: String,
    val updatedAgo: (String) -> String,
    val justNow: String,
    val secondsAgo: (Long) -> String,
    val minutesAgo: (Long) -> String,
    val filterByLine: String,
    val vehicles: String,
    val monitoredVehicles: (Int) -> String,
    val noVehiclesFound: String,
    val headerLine: String,
    val headerDir: String,
    val headerDest: String,
    val headerArrival: String,
    val headerDist: String,
    val vehicleRef: (String) -> String,
    val distanceMeters: (Int) -> String,
    val fullArrival: (String) -> String,
    val showOnMap: String,
    val arrivalNow: String,
    val arrivalInMin: (Long) -> String,
    val connectingToServer: String,
    val connectionFailed: String,
    val serversTried: (String) -> String,
    val noServerReachable: String,
    val useCurrentLocation: String,
    val clear: String,
    val locationIconDot: String,
    val locationIconPerson: String,
    val debugSettings: String,
    val debugDescription: String,
    val autoSearchRoutes: String,
    val expandBottomSheet: String,
    val save: String,
    val debugFill: String,
    val showPanel: String,
    val issueClarifier: String,
    val notAvailable: String,
    val nextArrival: String,
    val followMyLocation: String,
    val earlier: String,
    val later: String,
    val fastest: String,
    val fewerTransfers: String,
    val lessWalking: String,
    val fareEstimate: (String) -> String,
    val nearbyStops: String,
    val noNearbyStops: String,
    val walkingDistance: (Int) -> String,
    val serviceAlerts: String,
    val noAlerts: String,
    val peakHoursNotice: String,
    val normalServiceNotice: String,
    val favorites: String,
    val favoriteLines: String,
    val favoriteStations: String,
    val noFavorites: String,
    val addedToFavorites: String,
    val removedFromFavorites: String,
    val frequentRoute: String,
    val quickRoute: (String, String) -> String,
    val trackBus: String,
    val trackingBus: String,
    val stopTracking: String,
    val busLocationUpdated: String,
    val departureReminder: String,
    val reminderSet: (String) -> String,
    val reminderCancelled: String,
    val cancelReminder: String,
    val reminderNotification: (String, String) -> String,
    val minutesBefore: (Int) -> String,
    val linesBrowser: String,
    val searchLine: String,
    val viewLine: String,
    val direction: (String) -> String,
    val lineShape: String,
    val noShapeData: String,
    val timetable: String,
    val commonLines: String,
    val saveAs: String,
    val home: String,
    val work: String,
    val selectedLocation: String,
)

val EnStrings = AppStrings(
    routePlanner = "Route Planner",
    stationArrivals = "Station Arrivals",
    settings = "Settings",
    opacitySettings = "Opacity Settings",
    hideOpacitySettings = "Hide Opacity Settings",
    sheet = "Sheet",
    cards = "Cards",
    from = "From",
    to = "To",
    swapOriginDestination = "Swap origin and destination",
    searchRoutes = "Search Routes",
    searchingRoutes = "Searching routes...",
    retry = "Retry",
    now = "Now",
    departAt = "Depart At",
    arriveBy = "Arrive By",
    next = "Next",
    cancel = "Cancel",
    ok = "OK",
    direct = "Direct",
    transferCount = { n -> "$n transfer${if (n > 1) "s" else ""}" },
    walkDescription = { dur, dest -> "Walk $dur to $dest" },
    transitDescription = { mode, route, dest, dur -> "$mode$route toward $dest — $dur" },
    showStops = { n -> "Show $n stops" },
    hideStops = { n -> "Hide $n stops" },
    walkMode = "Walk",
    busMode = "Bus",
    trainMode = "Train",
    tramMode = "Tram",
    subwayMode = "Subway",
    ferryMode = "Ferry",
    formatDuration = { seconds ->
        val mins = seconds / 60
        when {
            mins < 60 -> "$mins min"
            mins % 60 == 0L -> "${mins / 60}h"
            else -> "${mins / 60}h ${mins % 60}min"
        }
    },
    station = "Station",
    updatedAgo = { ago -> "Updated $ago" },
    justNow = "just now",
    secondsAgo = { s -> "${s}s ago" },
    minutesAgo = { m -> "${m}m ago" },
    filterByLine = "Filter by line",
    vehicles = "Vehicles",
    monitoredVehicles = { n -> "Monitored Vehicles: $n" },
    noVehiclesFound = "No vehicles found",
    headerLine = "Line",
    headerDir = "Dir",
    headerDest = "Dest",
    headerArrival = "Arrival",
    headerDist = "Dist",
    vehicleRef = { ref -> "Vehicle: $ref" },
    distanceMeters = { m -> "Distance: ${m}m" },
    fullArrival = { t -> "Full arrival: $t" },
    showOnMap = "Show on map",
    arrivalNow = "now",
    arrivalInMin = { m -> "in ${m}min" },
    connectingToServer = "Connecting to PT server...",
    connectionFailed = "Connection failed",
    serversTried = { s -> "Servers tried: $s" },
    noServerReachable = "No PT server reachable",
    useCurrentLocation = "Use current location",
    clear = "Clear",
    locationIconDot = "Location: Blue Dot",
    locationIconPerson = "Location: Person",
    debugSettings = "Debug Settings",
    debugDescription = "Configure what happens when the debug button is tapped.",
    autoSearchRoutes = "Auto-search routes",
    expandBottomSheet = "Expand bottom sheet",
    save = "Save",
    debugFill = "Debug fill",
    showPanel = "Show panel",
    issueClarifier = "Issue Clarifier",
    notAvailable = "N/A",
    nextArrival = "Next Arrival",
    followMyLocation = "Follow my location",
    earlier = "Earlier",
    later = "Later",
    fastest = "Fastest",
    fewerTransfers = "Fewer transfers",
    lessWalking = "Less walking",
    fareEstimate = { amount -> "~$amount" },
    nearbyStops = "Nearby Stops",
    noNearbyStops = "No stops found nearby",
    walkingDistance = { m -> "${m}m walk" },
    serviceAlerts = "Service Alerts",
    noAlerts = "No active alerts",
    peakHoursNotice = "Peak hours — expect delays on busy lines",
    normalServiceNotice = "All lines operating normally",
    favorites = "Favorites",
    favoriteLines = "Favorite Lines",
    favoriteStations = "Favorite Stations",
    noFavorites = "No favorites yet",
    addedToFavorites = "Added to favorites",
    removedFromFavorites = "Removed from favorites",
    frequentRoute = "Quick Route",
    quickRoute = { from, to -> "$from → $to" },
    trackBus = "Track Bus",
    trackingBus = "Tracking...",
    stopTracking = "Stop Tracking",
    busLocationUpdated = "Bus location updated",
    departureReminder = "Departure Reminder",
    reminderSet = { time -> "Reminder set for $time" },
    reminderCancelled = "Reminder cancelled",
    cancelReminder = "Cancel reminder",
    reminderNotification = { line, time -> "Bus $line departs at $time" },
    minutesBefore = { m -> "${m}min before" },
    linesBrowser = "Lines",
    searchLine = "Search line number",
    viewLine = "View",
    direction = { d -> "Direction $d" },
    lineShape = "Line Route",
    noShapeData = "No route data available",
    timetable = "Timetable",
    commonLines = "Common Lines",
    saveAs = "Save as",
    home = "Home",
    work = "Work",
    selectedLocation = "Selected location",
)

val HeStrings = AppStrings(
    routePlanner = "תכנון מסלול",
    stationArrivals = "הגעות לתחנה",
    settings = "הגדרות",
    opacitySettings = "הגדרות שקיפות",
    hideOpacitySettings = "הסתר הגדרות שקיפות",
    sheet = "גיליון",
    cards = "כרטיסים",
    from = "מוצא",
    to = "יעד",
    swapOriginDestination = "החלף מוצא ויעד",
    searchRoutes = "חפש מסלולים",
    searchingRoutes = "מחפש מסלולים...",
    retry = "נסה שוב",
    now = "עכשיו",
    departAt = "יציאה ב",
    arriveBy = "הגעה עד",
    next = "הבא",
    cancel = "ביטול",
    ok = "אישור",
    direct = "ישיר",
    transferCount = { n -> "$n ${if (n > 1) "החלפות" else "החלפה"}" },
    walkDescription = { dur, dest -> "הליכה $dur אל $dest" },
    transitDescription = { mode, route, dest, dur -> "$mode$route לכיוון $dest — $dur" },
    showStops = { n -> "הצג $n תחנות" },
    hideStops = { n -> "הסתר $n תחנות" },
    walkMode = "הליכה",
    busMode = "אוטובוס",
    trainMode = "רכבת",
    tramMode = "רכבת קלה",
    subwayMode = "מטרו",
    ferryMode = "מעבורת",
    formatDuration = { seconds ->
        val mins = seconds / 60
        when {
            mins < 60 -> "$mins דק׳"
            mins % 60 == 0L -> "${mins / 60} שע׳"
            else -> "${mins / 60} שע׳ ${mins % 60} דק׳"
        }
    },
    station = "תחנה",
    updatedAgo = { ago -> "עודכן $ago" },
    justNow = "הרגע",
    secondsAgo = { s -> "לפני $s שנ׳" },
    minutesAgo = { m -> "לפני $m דק׳" },
    filterByLine = "סנן לפי קו",
    vehicles = "כלי רכב",
    monitoredVehicles = { n -> "כלי רכב במעקב: $n" },
    noVehiclesFound = "לא נמצאו כלי רכב",
    headerLine = "קו",
    headerDir = "כיוון",
    headerDest = "יעד",
    headerArrival = "הגעה",
    headerDist = "מרחק",
    vehicleRef = { ref -> "רכב: $ref" },
    distanceMeters = { m -> "מרחק: $m מ׳" },
    fullArrival = { t -> "הגעה מלאה: $t" },
    showOnMap = "הצג במפה",
    arrivalNow = "עכשיו",
    arrivalInMin = { m -> "בעוד $m דק׳" },
    connectingToServer = "...מתחבר לשרת PT",
    connectionFailed = "החיבור נכשל",
    serversTried = { s -> "שרתים שנוסו: $s" },
    noServerReachable = "לא ניתן להתחבר לשרת PT",
    useCurrentLocation = "השתמש במיקום נוכחי",
    clear = "נקה",
    locationIconDot = "מיקום: נקודה כחולה",
    locationIconPerson = "מיקום: דמות",
    debugSettings = "הגדרות דיבאג",
    debugDescription = "הגדר מה קורה כאשר כפתור הדיבאג נלחץ.",
    autoSearchRoutes = "חיפוש מסלולים אוטומטי",
    expandBottomSheet = "הרחב חלונית תחתונה",
    save = "שמור",
    debugFill = "מילוי דיבאג",
    showPanel = "הצג חלונית",
    issueClarifier = "דיווח על בעיה",
    notAvailable = "לא זמין",
    nextArrival = "הגעה הבאה",
    followMyLocation = "עקוב אחרי המיקום שלי",
    earlier = "מוקדם יותר",
    later = "מאוחר יותר",
    fastest = "המהיר ביותר",
    fewerTransfers = "פחות החלפות",
    lessWalking = "פחות הליכה",
    fareEstimate = { amount -> "~$amount" },
    nearbyStops = "תחנות קרובות",
    noNearbyStops = "לא נמצאו תחנות בסביבה",
    walkingDistance = { m -> "${m} מ׳ הליכה" },
    serviceAlerts = "התראות שירות",
    noAlerts = "אין התראות פעילות",
    peakHoursNotice = "שעות עומס — צפו לעיכובים בקווים עמוסים",
    normalServiceNotice = "כל הקווים פועלים כסדרם",
    favorites = "מועדפים",
    favoriteLines = "קווים מועדפים",
    favoriteStations = "תחנות מועדפות",
    noFavorites = "אין מועדפים עדיין",
    addedToFavorites = "נוסף למועדפים",
    removedFromFavorites = "הוסר מהמועדפים",
    frequentRoute = "מסלול מהיר",
    quickRoute = { from, to -> "$from → $to" },
    trackBus = "עקוב אחרי אוטובוס",
    trackingBus = "עוקב...",
    stopTracking = "הפסק מעקב",
    busLocationUpdated = "מיקום האוטובוס עודכן",
    departureReminder = "תזכורת יציאה",
    reminderSet = { time -> "תזכורת נקבעה ל-$time" },
    reminderCancelled = "תזכורת בוטלה",
    cancelReminder = "בטל תזכורת",
    reminderNotification = { line, time -> "אוטובוס $line יוצא ב-$time" },
    minutesBefore = { m -> "$m דק׳ לפני" },
    linesBrowser = "קווים",
    searchLine = "חפש מספר קו",
    viewLine = "הצג",
    direction = { d -> "כיוון $d" },
    lineShape = "מסלול קו",
    noShapeData = "אין נתוני מסלול",
    timetable = "לוח זמנים",
    commonLines = "קווים נפוצים",
    saveAs = "שמור בתור",
    home = "בית",
    work = "עבודה",
    selectedLocation = "מיקום נבחר",
)

val LocalAppStrings = compositionLocalOf { EnStrings }
